version: '3'

services:
  nextjs-app:
    build: ./nextjs-app
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs-app:/usr/src/app
    environment:
      NODE_ENV: production
    depends_on:
      - websocket-server

  websocket-server:
    build: ./websocket-server
    ports:
      - "8080:8080"
    volumes:
      - ./websocket-server:/usr/src/app

networks:
  app-network:
    driver: bridge
